name: Post Yuan Rate to VK

on:
  schedule:
    - cron: '15 17 * * *'  # Запуск каждый день в 12:00 МСК (9:00 UTC)
  workflow_dispatch:

jobs:
  post-to-vk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        run: python bot.py
